//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandlordDesktopApp.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Property
    {
        public int PropertyId { get; set; }
        public string Housenumber { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string PostCode { get; set; }
        public System.DateTime AvailableFrom { get; set; }
        public string Status { get; set; }
        public int LandlordId { get; set; }
    
        public virtual Landlord Landlord { get; set; }
    }
}
